service: export-data-into-excel
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"
            
functions:
  exportDataIntoExcel:
    handler: handlers/export_data_into_excel.handler
    layers: arn:aws:lambda:ap-south-1:625209709588:layer:nodeLayer:1
    events:
      - http:
          path: get-excel
          method: get
          cors: true